#!/bin/bash

# This script generates a random password
# This user can set the password length with -l and add a speacial character with -s
# Verbose mode can be enables with -v

usage() {
        echo "Usage: ${0} [-vs] [-l LENGTH]" >&2
        echo 'Generate a random password'
        echo ' -l LENGTH specify the password length'
        echo ' -s        append a special character to the  password'
        echo ' -v        Increase verbosity.'
        exit 1
}

log() {
        local MESSAGE="${@}"
        if [[ "${VERBOSE}" = 'true' ]]
        then
                echo "${MESSAGE}"
        fi
}
# Set a default password length
LENGTH=48

while getopts vl:s OPTION
do
        case ${OPTION} in
                v)
                        VERBOSE='true'
                        log 'Verbose mode on'
                        ;;
                l)
                        LENGTH="$OPTARG"
                        ;;
                s)
                        USE_SPECIAL_CHARACTER='true'
                        ;;
                ?)
                        usage
                        ;;
        esac
done

log 'Generating the password'

PASSWORD=$(date +%s%N${RANDOM}${RANDOM} | sha256sum | head -c ${LENGTH})

# Append a speacial character if request to do so
if [[ "${USE_SPECIAL_CHARACTER}" = 'true' ]]
then
        log 'Selecting the random special character'
        SPECIAL_CHARACTER=$(echo '!@#$%^&*()_-+=' | fold -w1 | shuf | head -c1 )
        PASSWORD="${PASSWORD}${SPECIAL_CHARACTER}"
fi

log 'Done'
log 'Here is the password:'

# Display the password.
echo "${PASSWORD}"
exit 0
